[theme]
primaryColor = "#941100"           # Rojo oscuro/burdeos
backgroundColor = "#FFF1E5"        # El famoso color "salmón" del FT
secondaryBackgroundColor = "#F2E5DA" # Un tono más oscuro del mismo papel
textColor = "#333333"
font = "serif"                     # Le da el toque de "periódico"
